name: "Setup"
description: "Set up Node and install project dependencies"
inputs:
  node-version:
    description: Node version to set up
    required: false # Defaults to "node-version-file"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        check-latest: true
        cache: "npm"
        cache-dependency-path: "package-lock.json"
    - if: ${{ inputs.node-version != '23' }}
      run: npm ci
      shell: "bash"
    - if: ${{ inputs.node-version == '23' }}
      # release-it does not yet support Node 23, so we have to set --engine-strict=false and eat the warning.
      # See: https://github.com/release-it/release-it/issues/1173
      run: npm ci --engine-strict=false
      shell: "bash"
