name: NPM Audit

on:
  schedule:
    # Fridays 20:23 UTC / 12:23 PST / 13:23 PDT
    - cron: "23 20 * * 5"

jobs:
  npm-audit:
    name: "NPM Audit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/set-up-ci
        # set audit level to High to ignore blocked updates till Node 18 is eol on 1 June 2025.
        # See: https://github.com/dmurvihill/motion-sdk/issues/37
      - run: npm audit --audit-level=$(if [ "$(date +%s)" -lt "1748736000" ]; then printf "high"; else printf "low"; fi)
