name: Check Rate Limits

on:
  schedule:
    # Mondays 10:00 UTC / 02:00 PST / 03:00 PDT
    - cron: "23 10 * * 1"

jobs:
  verify-rate-limits:
    name: "Verify Rate Limits"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/set-up-ci
        with:
          node-version: 22
      - run: npm run test -- __tests__/motion-rate-limits.test.ts --collectCoverage=false --testPathIgnorePatterns=""
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_USER: ${{ secrets.REDIS_USER }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          MOTION_USER_ID: ${{ secrets.MOTION_USER_ID }}
          MOTION_API_KEY: ${{ secrets.MOTION_API_KEY }}
