name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/set-up-ci
      - run: npx prettier --check .
      - run: npm run lint -- --max-warnings 0

  test:
    concurrency: "targets-the-motion-api"
    strategy:
      max-parallel: 1
      matrix:
        node-version: [20, 22, 23]

    env:
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_USER: ${{ secrets.REDIS_USER }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      MOTION_USER_ID: ${{ secrets.MOTION_USER_ID }}
      MOTION_API_KEY: ${{ secrets.MOTION_API_KEY }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/set-up-ci
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm test
      - run: npm run test:live
      - run: sleep 60

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/set-up-ci
      - run: npm run build
